### ISSUE TITLE
error build rom

### ISSUE THREAD

**Issue by ieprst** [ShivamKumarJha/android_device_xiaomi_tulip#1]
[ 99% 1452/1453] glob vendor/qcom/open...erfaces/wifi/supplicant/1.0/Android.bp
ninja: error: 'INSTALLED_KERNEL_HEADERS', needed by '/home/alex/crDroid/out/target/product/tulip/obj/SHARED_LIBRARIES/libcryptfs_hw_intermediates/cryptfs_hw.o', missing and no known rule to make it
13:06:14 ninja failed with: exit status 1

**Comment by taranhora** [comment]
Just use sdm660 kernel to build
